name: Build Test

on:
  push:
    branches:
      - '*'
      - '!pelican'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Configura python
        uses: actions/setup-python@v4
        with:
          python-version: "2.7"
          cache: pip
      
      - name: Instala dependências
        run: pip install -r requirements.txt

      - name: Build do site
        run: make publish
